Repository I-O-Benchmark-On-Container/ContainerTracer, pull requests merged in 2020-08, with the labels that each got.

#3 컴파일 규칙 추가, cppcheck 및 clang-format의 동작 과정 일원화
  .travis.yml
  README.md
  SConstruct
  include/SConscript
  runner/SConscript
  runner/test/SConscript
  trace-replay/SConscript
  trace-replay/test/SConscript
Labels: enhancement

#5 [Parser] IPC를 활용한 로그 전송
  include/trace_replay.h
  trace-replay/trace_replay.c
Labels: feature

#4 runner 초기화 과정의 구현
  include/generic.h
  include/runner.h
  include/tr-driver.h
  runner/generic.c
  runner/runner.c
  runner/test/SConscript
  runner/test/runner-test.c
  runner/tr-driver.c
  unity/unity.c
Labels: feature

#12 [Parser] 메모리 이슈 일부 해결 및 불필요한 코드 제거
  trace-replay/trace_replay.c
Labels: enhancement

#11 [Runner] Trace-Replay 드라이버 및 Runner 구현 완료
  README.md
  SConstruct
  include/.gitignore
  include/driver/tr-driver.h
  include/log.h
  include/runner.h
  include/sync.h
  include/tr-driver.h
  include/trace_replay.h
  runner/SConscript
  runner/driver/tr-driver/tr-driver.c
  runner/driver/tr-driver/tr-info.c
  runner/driver/tr-driver/tr-mq.c
  runner/driver/tr-driver/tr-serializer.c
  runner/driver/tr-driver/tr-shm.c
  runner/generic.c
  runner/main.c
  runner/runner.c
  runner/test/SConscript
  runner/test/runner-test.c
  runner/tr-driver.c
  setting/SConscript
  trace-replay/SConscript
  trace-replay/test/SConscript
  unity/.gitignore
  unity/unity.o
Labels: enhancement, feature

#14 [Runner] 동적 메모리 해제 이후의 접근하는 문제 해결 및 각종 버그 해결
  include/driver/tr-driver.h
  runner/driver/tr-driver/tr-driver.c
Labels: bug

#16 [Runner] `runner-test.c`의 JSON 출력 방식 개선 및 `memcpy` 관련 문제 해결
  runner/driver/tr-driver/tr-driver.c
  runner/test/runner-test.c
Labels: enhancement

#17 [ALL+Runner] 컴파일러 변경 및 Doxyfile 추가, Runner 소스 코드 문서화 진행
  .travis.yml
  Doxyfile
  README.md
  SConstruct
  include/driver/tr-driver.h
  include/generic.h
  include/runner.h
  include/sync.h
  runner/driver/tr-driver/tr-driver.c
  runner/driver/tr-driver/tr-info.c
  runner/driver/tr-driver/tr-mq.c
  runner/driver/tr-driver/tr-serializer.c
  runner/driver/tr-driver/tr-shm.c
  runner/generic.c
  runner/runner.c
  runner/test/runner-test.c
Labels: documentation, enhancement, feature

#18 [Runner] Flawfinder의 지적 사항 및 README.md 일부 수정 진행
  README.md
  runner/driver/tr-driver/tr-driver.c
  runner/driver/tr-driver/tr-info.c
  runner/driver/tr-driver/tr-mq.c
  runner/driver/tr-driver/tr-serializer.c
  runner/driver/tr-driver/tr-shm.c
  runner/runner.c
  runner/test/runner-test.c
Labels: enhancement

#22 [Runner] errno의 잘못된 할당 방식을 개선했습니다.
  runner/runner.c
Labels: bug

#23 [Frontend] `.travis.yml`에 `flask_socketio`를 업데이트했습니다.
  .travis.yml
Labels: bug, draft

#29 [Runner] 불필요한 `goto` 구문의 삭제
  runner/driver/tr-driver/tr-driver.c
  runner/driver/tr-driver/tr-info.c
  runner/driver/tr-driver/tr-mq.c
  runner/driver/tr-driver/tr-shm.c
Labels: enhancement

#32 [Runner] `sync.h`의 다중 인클루드 실패 문제 해결
  include/sync.h
Labels: bug

#34 [ALL] 자동 설치를 할 수 있도록 빌드 파일을 수정했습니다.
  README.md
  runner/SConscript
  trace-replay/SConscript
Labels: enhancement

#41 [Runner] tr-driver-test의 버그 수정 및 docker-driver 개선
  runner/driver/docker-driver/docker-driver.c
  runner/test/docker-driver-test.c
  runner/test/tr-driver-test.c
Labels: bug, enhancement

#43 [Runner] .travis.ci 컴파일러 변경 및 docker-driver 버그 수정
  .travis.yml
  SConstruct
  runner/driver/docker-driver/docker-driver.c
  runner/test/docker-driver-test.c
  runner/test/tr-driver-test.c
Labels: bug, enhancement

#44 [ALL] Changing Korean description to English.
  CONTRIBUTING.md
  Doxyfile
  README.md
  SConstruct
  documentation/README-KOR.md
  include/driver/docker-driver.h
  include/driver/tr-driver.h
  include/generic.h
  include/log.h
  include/runner.h
  include/sync.h
  runner/driver/docker-driver/docker-driver.c
  runner/driver/docker-driver/docker-info.c
  runner/driver/docker-driver/docker-mq.c
  runner/driver/docker-driver/docker-serializer.c
  runner/driver/docker-driver/docker-shm.c
  runner/driver/tr-driver/tr-driver.c
  runner/driver/tr-driver/tr-info.c
  runner/driver/tr-driver/tr-mq.c
  runner/driver/tr-driver/tr-serializer.c
  runner/driver/tr-driver/tr-shm.c
  runner/generic.c
  runner/runner.c
  runner/test/docker-driver-test.c
  runner/test/tr-driver-test.c
  setting/SConscript
Labels: documentation

#45 [ALL] Fix the miss typo of the parameter in docker-shm.c
  runner/driver/docker-driver/docker-shm.c
Labels: documentation

#47 [ALL] Fix the broken link in README.md
  README.md
  documentation/README-KOR.md
Labels: bug, documentation

#51 [ALL] Add the `LINKFLAGS` to `SConstruct` file.
  SConstruct
Labels: documentation

#52 [ALL] Change the setting of Doxyfile.
  Doxyfile
Labels: documentation

#54 [ALL] Adds the ignore cases in `.gitignore` file.
  .gitignore
Labels: documentation

#53 [Frontend] Reflect backend data & ADD toast message
  web/package/__init__.py
  web/package/main/__init__.py
  web/package/main/events.py
  web/package/static/css/style.css
  web/package/static/js/common.js
  web/package/static/js/index.js
  web/package/static/js/result.js
  web/package/templates/index.html
Labels: feature

#55 [ALL] Adds the `web` directory to Doxyfile.
  Doxyfile
Labels: documentation

#57 [Backend] Factory method and validation checking applied
  web/package/__init__.py
  web/package/chart.py
  web/package/container_tracer.py
  web/package/container_tracer_factory.py
  web/package/main/__init__.py
  web/package/main/events.py
  web/package/main/routes.py
  web/package/templates/index.html
  web/package/trace_replay.py
  web/package/tracereplay.py
Labels: feature

#61 [Runner] Did eliminate the duplicate code in the `docker` driver.
  runner/driver/docker-driver/docker-driver.c
Labels: refactoring

#62 [Runner] Fix the `tr-driver` and enhance the `docker-driver`.
  include/runner.h
  runner/driver/docker-driver/docker-driver.c
  runner/driver/tr-driver/tr-driver.c
  runner/test/docker-driver-test.c
  runner/test/tr-driver-test.c
Labels: bug, enhancement, refactoring

#64 [Frontend] Fix the javascript bug and enhance the HTML
  .gitignore
  web/package/static/js/result.js
  web/package/templates/index.html
Labels: bug, enhancement

#65 [Trace-replay] Fix the message exceeded issue.
  trace-replay/trace_replay.c
Labels: bug

#67 [ALL] Add the `web` information on the `README.md`
  README.md
  documentation/README-KOR.md
Labels: documentation

#68 [Backend] Add more exception handling.
  web/package/main/events.py
  web/package/trace_replay.py
Labels: enhancement

#69 [Runner -> Docker driver] #60 issue handling on docker container
  runner/driver/docker-driver/docker-driver.c
  runner/test/docker-driver-test.c
  runner/test/tr-driver-test.c
Labels: bug

#71 [Runner] Reduce the docker-driver's CC.
  runner/driver/docker-driver/docker-driver.c
Labels: refactoring

#72 [ALL] Update the version of Doxyfile (v0.0.1 → v0.1)
  Doxyfile
Labels: documentation

#74 [ALL] Add the sample video to README.md
  README.md
  documentation/README-KOR.md
Labels: documentation

#75 [Runner] Refactor the docker-driver and tr-driver, runner.
  include/driver/docker-driver.h
  include/driver/tr-driver.h
  runner/driver/docker-driver/docker-driver.c
  runner/driver/docker-driver/docker-info.c
  runner/driver/tr-driver/tr-driver.c
  runner/driver/tr-driver/tr-info.c
  runner/runner.c
Labels: bug, refactoring

#76 [Runner] Change the trace-replay binary file finding sequence
  runner/driver/docker-driver/docker-info.c
  runner/driver/tr-driver/tr-driver.c
Labels: bug
